modLoader="javafml" #mandatory
loaderVersion="[39,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
license="MIT License"
[[mods]] #mandatory
# The modid of the mod
modId="autopaletteexamplemod" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Autopalette Example Mod" #mandatory
credits="I hear the Minecraft Mod Development discord channel is the cat's bananas" #optional
authors="Commoble"
description='''
Example mod showing how to use autopalette jsons to generate textures at pack-load time
'''
